"""Add unique constraint for the documents table.

Revision ID: 1edfc4f60e2b
Revises: c1b067d0d9e2
Create Date: 2026-05-09 21:15:53.428439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1edfc4f60e2b'
down_revision: Union[str, Sequence[str], None] = 'c1b067d0d9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'documents', 'uploaded_by', existing_type=sa.UUID(), nullable=False
    )
    op.create_unique_constraint(
        'unique_file_user', 'documents', ['file_name', 'uploaded_by']
    )
    op.drop_constraint(
        op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(
        op.f('documents_uploaded_by_fkey'),
        'documents',
        'users',
        ['uploaded_by'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_constraint('unique_file_user', 'documents', type_='unique')
    op.alter_column(
        'documents', 'uploaded_by', existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
