"""create relationship between collection and document

Revision ID: 9f3d295dbd20
Revises: 1edfc4f60e2b
Create Date: 2026-05-11 23:23:22.044352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9f3d295dbd20'
down_revision: Union[str, Sequence[str], None] = '1edfc4f60e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents', sa.Column('collection_id', sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None,
        'documents',
        'collections',
        ['collection_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'collection_id')
    # ### end Alembic commands ###
