"""Add constraints for the collection table.

Revision ID: c1b067d0d9e2
Revises: 254aa335251d
Create Date: 2026-05-09 00:55:57.040595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c1b067d0d9e2'
down_revision: Union[str, Sequence[str], None] = '254aa335251d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'collections', ['collection_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='unique')
    # ### end Alembic commands ###
